management:
  endpoints:
    web:
      exposure:
        include: "*"
        
spring:
  cache:
    type: redis
  redis:    host: ${RHOST}
    port: ${RPORT}
    password: ${RPASSWORD}
urls: 
  account-service: ${ACCOUNTSERVICE}
  restart-service: ${RESTARTSERVICE}